nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PATCH', 'DELETE']
        max_age: 3600
    paths:
        '^/': null
